iesi:
  metadata:
    component-types:
      default:
        description: Default component type
        parameters: {}
      http.request:
        description: Http request component type
        parameters:
          connection:
            description: connection
            type: string
            mandatory: true
            encrypted: false
          endpoint:
            description: url
            type: string
            mandatory: false
            encrypted: false
          type:
            description: type of HTTP Request
            type: string
            mandatory: true
            encrypted: false
          queryParam:
            description: queryParam
            type: string
            mandatory: false
            encrypted: false
          header:
            description: header
            type: string
            mandatory: false
            encrypted: false
